### ISSUE TITLE
Proof that the interface allows readers without writing anything to memory (SeqLock)

### ISSUE THREAD

**Issue by anton-malakhov** [BlazingPhoenix/concurrent-hash-map#1]

**Comment by anton-malakhov** [comment]
Please put the revision link here where it has been implemented

**Comment by BlazingPhoenix** [comment]
https://github.com/BlazingPhoenix/concurrent-hash-map/commit/070055354ef574f081689a95feeca7016fff939f

**Comment by anton-malakhov** [comment]
So, the lock and version are still not joined: https://github.com/BlazingPhoenix/concurrent-hash-map/blob/master/concurrent_hash_map/concurrent_hash_map.hpp#L476-L477
Is it actually thread safe and no atomicy problems? I wonder if it will be faster if placed in one word (64 bits) as in the prototype

**Comment by BlazingPhoenix** [comment]
It is another counter. It is used to estimate number of elements in a bucket. It isn't what you think. Probably we should separate it from into another abstraction.

**Comment by anton-malakhov** [comment]
I see, I'm sorry. Though, this counter there is not a good idea from component isolation point of view - a synchronizer job is to synchronize, not to count elements
